# Generated by Django 3.2.6 on 2021-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=50)),
                ('pl_age', models.IntegerField()),
                ('pl_number', models.IntegerField()),
                ('pl_image', models.CharField(default='https://www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg', max_length=2000)),
            ],
        ),
    ]
