# Generated by Django 3.2.6 on 2021-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='pl_position',
            field=models.CharField(default='cam', max_length=25),
        ),
    ]
