# Generated by Django 3.2.6 on 2021-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_players_pl_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_name', models.CharField(max_length=100)),
                ('leg_age', models.IntegerField()),
                ('leg_image', models.CharField(default='.....', max_length=1000)),
                ('leg_play', models.CharField(max_length=100)),
            ],
        ),
    ]
