# Generated by Django 3.2.6 on 2021-09-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_legends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Womens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('image', models.CharField(max_length=2000)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
